openapi: 3.0.3
info:
  title: Purpose Process Micro Service
  description: Offers operations to retrieve purpose data
  version: '{{version}}'
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: support@example.com
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: '/pdnd-interop-uservice-purpose-process/{{version}}'
    description: This service is the purpose process
security:
  - bearerAuth: [ ]
tags:
  - name: purpose
    description: Implements purpose process
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: health
    description: Verify service status
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /purposes:
    get:
      tags:
        - purpose
      operationId: getPurposes
      description: Retrieve Purposes
      parameters:
        - in: query
          name: eserviceId
          schema:
            type: string
            format: uuid
        - in: query
          name: consumerId
          schema:
            type: string
            format: uuid
        - in: query
          name: states
          description: comma separated sequence of states to filter the response with
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PurposeVersionState'
            default: [ ]
          explode: false
      responses:
        '200':
          description: Purposes requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purposes'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - purpose
      operationId: createPurpose
      description: Creates the Purpose
      responses:
        '201':
          description: Purpose created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purpose'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurposeSeed'
        required: true
  /purposes/{id}:
    parameters:
      - name: id
        in: path
        description: the purpose id
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - purpose
      operationId: getPurpose
      description: Retrieve the Purpose
      responses:
        '200':
          description: Purpose requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purpose'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Purpose Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /status:
    get:
      tags:
        - health
      summary: Health status endpoint
      description: Return ok
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /purposes/{purposeId}/versions/{versionId}/suspend:
    parameters:
      - name: purposeId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
      - name: versionId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
    post:
      summary: Suspend Purpose Version
      operationId: suspendPurposeVersion
      responses:
        '204':
          description: Purpose Version Suspended
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Purpose Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      tags:
        - purpose
      description: suspends the purpose version by id
  /purposes/{purposeId}/versions/{versionId}/waitForApproval:
    parameters:
      - name: purposeId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
      - name: versionId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
    post:
      summary: Wait for Approval for Purpose Version
      operationId: waitForApprovalPurposeVersion
      responses:
        '204':
          description: Purpose Version In Waiting for Approval
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Purpose Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      tags:
        - purpose
      description: waits for approval for the purpose version by id
  /purposes/{purposeId}/versions/{versionId}/archive:
    parameters:
      - name: purposeId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
      - name: versionId
        in: path
        required:
          true
        schema:
          type: string
          format: uuid
    post:
      summary: Archive Purpose Version
      operationId: archivePurposeVersion
      responses:
        '204':
          description: Purpose Version Archived
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Purpose Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      tags:
        - purpose
      description: archives the purpose version by id
components:
  schemas:
    Purpose:
      type: object
      properties:
        id:
          type: string
          format: uuid
        eserviceId:
          type: string
          format: uuid
        consumerId:
          type: string
          format: uuid
        versions:
          type: array
          items:
            $ref: '#/components/schemas/PurposeVersion'
        suspendedByConsumer:
          type: boolean
        suspendedByProducer:
          type: boolean
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - eserviceId
        - consumerId
        - versions
        - title
        - createdAt
      description: business representation of a purpose
    Purposes:
      type: object
      properties:
        purposes:
          type: array
          items:
            $ref: '#/components/schemas/Purpose'
      required:
        - purposes
    PurposeVersion:
      type: object
      properties:
        id:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/PurposeVersionState'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        expectedApprovalDate:
          type: string
          format: date-time
        riskAnalysis:
          $ref: '#/components/schemas/PurposeVersionDocument'
      required:
        - id
        - state
        - createdAt
      description: business representation of a purpose version
    PurposeVersionState:
      type: string
      description: Purpose State
      enum:
        - ACTIVE
        - DRAFT
        - SUSPENDED
        - WAITING_FOR_APPROVAL
        - ARCHIVED
    PurposeVersionDocument:
      type: object
      required:
        - id
        - contentType
        - path
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        contentType:
          type: string
        createdAt:
          type: string
          format: date-time
    PurposeSeed:
      type: object
      description: contains the expected payload for purpose creation.
      properties:
        eserviceId:
          type: string
          format: uuid
        consumerId:
          type: string
          format: uuid
        riskAnalysisForm:
          $ref: '#/components/schemas/RiskAnalysisForm'
        title:
          type: string
        description:
          type: string
      required:
        - eserviceId
        - consumerId
        - riskAnalysisForm
        - title
    RiskAnalysisForm:
      type: object
      properties:
        version:
          type: string
        answers:
          $ref: '#/components/schemas/RiskAnalysisFormAnswers'
      required:
        - version
        - answers
    RiskAnalysisFormAnswers:
      type: object
      properties:
        purpose:
          $ref: '#/components/schemas/RiskAnalysisFormTextAnswer'
        usesPersonalData:
          $ref: '#/components/schemas/FormUsesPersonalDataAnswers'
        usesThirdPartyPersonalData:
          $ref: '#/components/schemas/FormUsesThirdPartyPersonalDataAnswers'
        usesConfidentialData:
          $ref: '#/components/schemas/FormUsesConfidentialDataAnswers'
        securedDataAccess:
          $ref: '#/components/schemas/FormSecuredDataAccessAnswers'
        legalBasis:
          type: array
          items:
            $ref: '#/components/schemas/FormLegalBasisAnswers'
        legalObligationReference:
          $ref: '#/components/schemas/RiskAnalysisFormTextAnswer'
        publicInterestReference:
          $ref: '#/components/schemas/RiskAnalysisFormTextAnswer'
        knowsAccessedDataCategories:
          $ref: '#/components/schemas/FormKnowsAccessedDataCategoriesAnswers'
        accessDataArt9Gdpr:
          $ref: '#/components/schemas/FormAccessDataArt9GdprAnswers'
        accessUnderageData:
          $ref: '#/components/schemas/FormAccessUnderageDataAnswers'
        knowsDataQuantity:
          $ref: '#/components/schemas/FormKnowsDataQuantityAnswers'
        dataQuantity:
          $ref: '#/components/schemas/FormDataQuantityAnswers'
        deliveryMethod:
          $ref: '#/components/schemas/FormDeliveryMethodAnswers'
        doneDpia:
          $ref: '#/components/schemas/FormDoneDpiaAnswers'
        definedDataRetentionPeriod:
          $ref: '#/components/schemas/FormDefinedDataRetentionPeriodAnswers'
        purposePursuit:
          $ref: '#/components/schemas/FormPurposePursuitAnswers'
        checkedExistenceMereCorrectnessPdndCatalogue:
          type: array
          items:
            $ref: '#/components/schemas/FormCheckedExistenceMereCorrectnessPdndCatalogueAnswers'
        checkedAllDataNeeded:
          $ref: '#/components/schemas/FormCheckedAllDataNeededAnswers'
        checkedExistenceMinimalDataPdndCatalogue:
          $ref: '#/components/schemas/FormCheckedExistenceMinimalDataPdndCatalogueAnswers'
      required:
        - purpose
        - usesPersonalData
    RiskAnalysisFormTextAnswer:
      type: string
    FormUsesPersonalDataAnswers:
      type: string
      enum:
        - usesPersonalDataYes
        - usesPersonalDataNo
    FormUsesThirdPartyPersonalDataAnswers:
      type: string
      enum:
        - usesThirdPartyPersonalDataYes
        - usesThirdPartyPersonalDataNo
    FormUsesConfidentialDataAnswers:
      type: string
      enum:
        - usesConfidentialDataYes
        - usesConfidentialDataNo
    FormSecuredDataAccessAnswers:
      type: string
      enum:
        - securedDataAccessYes
        - securedDataAccessNo
    FormLegalBasisAnswers:
      type: string
      enum:
        - legalBasisConsent
        - legalBasisContract
        - legalBasisLegalObligation
        - legalBasisSafeguard
        - legalBasisPublicInterest
        - legalBasisLegitimateInterest
    FormKnowsAccessedDataCategoriesAnswers:
      type: string
      enum:
        - knowsAccessedDataCategoriesYes
        - knowsAccessedDataCategoriesNo
    FormAccessDataArt9GdprAnswers:
      type: string
      enum:
        - accessDataArt9GdprYes
        - accessDataArt9GdprNo
    FormAccessUnderageDataAnswers:
      type: string
      enum:
        - accessUnderageDataYes
        - accessUnderageDataNo
    FormKnowsDataQuantityAnswers:
      type: string
      enum:
        - knowsDataQuantityYes
        - knowsDataQuantityNo
    FormDataQuantityAnswers:
      type: string
      enum:
        - dataQuantity0To100
        - dataQuantity101To500
        - dataQuantity500To1000
        - dataQuantity1001To5000
        - dataQuantity5001Over
    FormDeliveryMethodAnswers:
      type: string
      enum:
        - deliveryMethodCleartext
        - deliveryMethodAggregate
        - deliveryMethodAnonymous
        - deliveryMethodPseudoanonymous
    FormDoneDpiaAnswers:
      type: string
      enum:
        - doneDpiaYes
        - doneDpiaNo
    FormDefinedDataRetentionPeriodAnswers:
      type: string
      enum:
        - definedDataRetentionPeriodYes
        - definedDataRetentionPeriodNo
    FormPurposePursuitAnswers:
      type: string
      enum:
        - purposePursuitMereCorrectness
        - purposePursuitNewPersonalData
    FormCheckedExistenceMereCorrectnessPdndCatalogueAnswers:
      type: string
      enum:
        - checkedExistencePdndCatalogueYes
    FormCheckedAllDataNeededAnswers:
      type: string
      enum:
        - checkedAllDataNeededYes
        - checkedAllDataNeededNo
    FormCheckedExistenceMinimalDataPdndCatalogueAnswers:
      type: string
      enum:
        - checkedExistenceMinimalDataPdndCatalogueYes
        - checkedExistenceMinimalDataPdndCatalogueNo
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    ProblemError:
      properties:
        code:
          description: Internal code of the error
          example: 123-4567
          minLength: 8
          maxLength: 8
          pattern: '^[0-9]{3}-[0-9]{4}$'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
      required:
        - code
        - detail
  securitySchemes:
    bearerAuth:
      type: http
      description: 'A bearer token in the format of a JWS and conformed to the specifications included in [RFC8725](https://tools.ietf.org/html/RFC8725).'
      scheme: bearer
      bearerFormat: JWT